service: sls-hills
app: sls-hills
org: wisesmile

provider:
  name: aws
  runtime: nodejs12.x

# you can add statements to the Lambda function's IAM Role here
#  iamRoleStatements:
#    - Effect: "Allow"
#      Action:
#        - "s3:ListBucket"
#      Resource: { "Fn::Join" : ["", ["arn:aws:s3:::", { "Ref" : "ServerlessDeploymentBucket" } ] ]  }
#    - Effect: "Allow"
#      Action:
#        - "s3:PutObject"
#      Resource:
#        Fn::Join:
#          - ""
#          - - "arn:aws:s3:::"
#            - "Ref" : "ServerlessDeploymentBucket"
#            - "/*"

# you can add packaging information here
#package:
#  include:
#    - include-me.js
#    - include-me-dir/**
#  exclude:
#    - exclude-me.js
#    - exclude-me-dir/**

plugins:
  - serverless-jest-plugin

functions:
  calc:
    handler: src/calc001/index.handler
    events:
      - http:
          path: calc
          method: get
          cors: true

  myFunction:
    handler: src/myFunction/index.handler
    events:
      - http:
          path: myFunc
          method: get
          cors: true

  hello:
    handler: handler.hello
    events:
      - http:
          path: hello
          method: get
          cors: true
