org: wisesmile
app: sls-hills
service: hills-s3

custom:
  bucket: hills-s3-test

provider:
  name: aws
  runtime: nodejs12.x
  iamRoleStatements:
    - Effect: Allow
      Action:
        - s3:PutObject
        - s3:PutObjectAcl
      Resource: "arn:aws:s3:::${self:custom.bucket}/*"

functions:
  save:
    handler: functions/alpha/save.handler
    environment:
      BUCKET: ${self:custom.bucket}