org: wisesmile
app: sls-hills
service: hills-s3

custom:
  bucket: hills-s3-test

provider:
  name: aws
  runtime: nodejs12.x
  iamRoleStatements:
    - Effect: Allow
      Action:
        - s3:PutObject
        - s3:PutObjectAcl
      Resource: "arn:aws:s3:::${self:custom.bucket}/*"

functions:
  save:
    handler: functions/write-to-s3/handler.save
    events:
      - http:
          path: /write-to-s3
          method: post
          cors: true
    environment:
      BUCKET: ${self:custom.bucket}